### ISSUE TITLE
该扩展依赖的 VS Code 相关 API 发生了变动

### ISSUE THREAD

**Issue by MapleCCC** [coolzilj/vscode-v2ex#1]
今天（2019.3.12 ）安装的时候弹出了以下错误信息。

> 扩展“coolzilj.vscode-v2ex”使用了 "vscode.previewHtml" 命令，而此命令已弃用且即将删除。请针对此扩展提交问题，从而更新为使用 VS Code 的 webview API。

**Comment by bhaltair** [comment]
command 'vscode.previewHtml' not found

**Comment by coolzilj** [comment]
`vscode.previewHtml` API 已经废弃了，需要改成 webview API，改动挺大的，没时间改。
